# date and model config

# ################################################################
#                             Data
# ################################################################
device: 'cuda:1' # calculate device
sampling_rate: 8000  # sampling rate
win_len: 256  # fft size(25ms padded)
hop: 80  # frame stride(10ms)
lowfreq: 50.0  # minimum cut-off frequency
highfreq: 2500.0 # maximum cut-off frequency
max_record_time: 16 # Maximum duration of each breath audio recording(Unit:s)
max_event_time: 3   # Maximum duration of each breath audio event(Unit:s)
train_feature: './feature_and_labels/train_feature.npy'
train_labels: './feature_and_labels/train_labels.npy'
eval_feature: './feature_and_labels/eval_feature.npy'
eval_labels: './feature_and_labels/eval_labels.npy'
test_feature: './feature_and_labels/test_feature.npy'
test_labels: './feature_and_labels/test_labels.npy'
seed: 666  # random seed

# ################################################################
#                             Model
# ################################################################

whisper_seq: 1500
whiper_dim: 384

encoder_dim: 256
num_encoder_layers: 16
num_attention_heads: 4

rnn_hid_dim: 512
rnn_layers: 2
bidirect: true

n_fc_layers: 2
fc_layer_dim: 1024

output_dim: 15

input_dropout: 0.1
feed_forward_dropout: 0.1
attention_dropout: 0.1
conv_dropout: 0.1
fc_layer_drop: 0.5
rtb_data_channels: 1

## ################################################################
##                             Experiment
## ################################################################

batch_size: 64
lr: 0.00001
momentum: 0.9
gamma: 2
epoch: 200
save_step: 200
verbose_step: 100
lr_reduce_step: 2000
lr_reduce_ratio: 0.1
